version: '3.8'

services:
  mongodb:
    image: "mongo"
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"

  backend:
    build: .
    container_name: backend_youtube
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: "mongodb://mongodb:27017"

volumes:
  mongodb_data:
